name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme myst-parser sphinx-js

      - name: Install Node.js dependencies
        run: |
          npm install -g jsdoc jsdoc-mermaid

      - name: Build Python documentation
        run: |
          cd docs
          make html

      - name: Build JavaScript documentation
        run: |
          cd frontend
          jsdoc -c jsdoc.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
